### ISSUE TITLE
Maximum of 15 blinds

### ISSUE THREAD

**Issue by knh1965** [gormanb/homebridge-connector-hub#5]
I have 2 DD7002B Connector Bridges operating 37 roller blinds.  One Connector Bridge has 22 the other 15.  Each Connector Bridge maxes out at 22 connected blinds.  I am able to use the plugin 2x by adding the IP address for each individual Connector Bridge to the plugin configuration, however, only have access to 30 blinds.

Are you able to increase the maximum blinds to 22 to match the Connector Bridge?

Thanks

**Comment by gormanb** [comment]
Hi @knh1965,

There's nothing in the plugin that enforces a limit of 15 blinds; it queries the hub for all connected devices, then creates an accessory for each one. I was under the impression that 15 was the limit - that's what we were told by the guy who installed our blinds - but some googling suggests that both the [DD7002B](https://www.hurricaneshutterswholesale.com/dooya-home-automation-smart-hub/) and the [DD1554](https://www.ismartwindow.co.nz/DD1554_mini_bridge.html) can both control up to 30 motors.

The only thing I can think of is that the hub may only return a maximum of 15 blinds per response. The plugin expects to receive a single message that contains everything, so if there's a second message being sent by the hub with the remaining devices, the plugin won't see it.

I only have 7 blinds myself, so I won't be able to test this theory. Would you be willing to try out some beta versions of the plugin and let me know how they behave? I'm planning to add support for multiple hubs/devices anyway, so you won't have to run two instances of the plugin anymore.

**Comment by knh1965** [comment]
I would definitely try some beta versions. I am very new to the home automation and have very little knowledge on the technical side but happy test what I can!  As an FYI, I am on a HOOBs device.

________________________________

**Comment by gormanb** [comment]
Hi @knh1965, apologies for the delay in responding. I've just published a beta version `1.0.8-beta.0` which has support for multiple hubs and for retrieving more than one device list from each hub, so I believe should be able to pick up the remaining blinds in your setup.  Could you please install this version and give it a try? Let me know what behaviour you observe!

**Comment by knh1965** [comment]
It added all 37 of the blinds on the 2 hubs.  Only required one of the IP addresses in the plugin.  In adding the blinds to Home, it brought over serial numbers or some unique identifier.  Had to change all names to add them to Home as Home would not accept special characters in the name.  Thanks

**Comment by fasif07** [comment]
Hi @gormanb. Thank you for putting this beta together. I have 17 blinds in total and all mapped through one hub.
I have been getting the following error after trying out the BETA:

[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0038
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0039
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0029
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002a
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002b
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002c
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002d
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002e
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002f
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0030
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0031
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0032
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0035
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0036
[19/04/2023, 09:08:59] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0037
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".
[19/04/2023, 09:08:59] [homebridge-connector-hub] **Child bridge process ended**

I am now running this as a child bridge. If i don't, it crashes the entire server. Atleast this way it just crashes itself and restarts after a few tries. It has been doing that every few minutes or so.

I renamed all my blinds but everytime it restarts it goes back to default names in homekit.

Thanks for all your efforts!

**Comment by fasif07** [comment]
Further to above. when it finally tries 10~15 times. It runs. I can change the names in Homekit. move the blinds etc. Everything works spot on. Then at random, the same error message appears and crashes the child bridge:

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".
[19/04/2023, 19:35:26] [homebridge-connector-hub] Child bridge process ended
[19/04/2023, 19:35:26] [homebridge-connector-hub] Process Ended. Code: 1, Signal: null
[19/04/2023, 19:35:33] [homebridge-connector-hub] Restarting Process...

I have downgraded to the last final version. That works flawlessly as direct and as a child bridge (However can only see 15 blinds).

Also reformatted my PI server. Restarted the Blinds Hub. No change. Hope this helps!

**Comment by gormanb** [comment]
Hi @fasif07 - I've just published a new beta version, `1.0.8-beta.1`, which I believe should resolve this problem. Can you give it a try and let me know if it works? @knh1965, this beta should also fix the problem you had with invalid names being generated for the devices.

**Comment by fasif07** [comment]
Still crashing here and there, I have noticed that I am not loosing the names of first 15 in Homekit even though the child server is crashing sometimes. 

Blind # 16 and Blind # 17 is defaulting back to original names and goes to the default room. Rest of them are at least saved.

[08/05/2023, 12:37:54] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 37-3c71bf6d7bac', 100 ]
Error: bind EADDRINUSE 0.0.0.0
    at node:dgram:359:20
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
[08/05/2023, 12:38:40] [homebridge-connector-hub] Child bridge process ended
[08/05/2023, 12:38:40] [homebridge-connector-hub] Process Ended. Code: 1, Signal: null
[08/05/2023, 12:38:47] [homebridge-connector-hub] Restarting Process...
[08/05/2023, 12:38:49] [homebridge-connector-hub] Launched child bridge with PID 17298
[08/05/2023, 12:38:49] Registering platform 'homebridge-connector-hub.ConnectorHub'
[08/05/2023, 12:38:49] [homebridge-connector-hub] Loaded homebridge-connector-hub v1.0.8-beta.1 child bridge successfully
[08/05/2023, 12:38:50] Loaded 17 cached accessories from cachedAccessories.0E309A342324.
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0029
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac002a
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac002b
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac002c
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac002d
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac002e
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac002f
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0030
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0031
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0032
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0033
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0034
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0035
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0036
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0037
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0038
[08/05/2023, 12:38:50] [homebridge-connector-hub] Loading accessory from cache: Connector Device 3c71bf6d7bac0039
[08/05/2023, 12:38:50] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-connector-hub) is running on port 45646.
[08/05/2023, 12:38:51] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 32-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:51] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 32-3c71bf6d7bac', 50 ]
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac0029
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac002a
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac002b
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac002c
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac002d
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac002e
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac002f
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac0030
[08/05/2023, 12:38:51] [homebridge-connector-hub] Periodic refresh failed: Connector Device 3c71bf6d7bac0031
[08/05/2023, 12:38:51] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 33-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:51] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 33-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:51] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 34-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:51] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 34-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 35-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 35-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 36-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 36-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 37-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 37-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 38-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 38-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 39-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 39-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0029
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002a
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002b
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002c
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002d
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002e
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac002f
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0030
[08/05/2023, 12:38:52] [homebridge-connector-hub] Failed to get position: Connector Device 3c71bf6d7bac0031
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 29-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 29-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 2a-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 2a-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 2b-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 2b-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 2c-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 2c-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 2d-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:55] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 2d-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 2e-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 2e-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 2f-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 2f-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 30-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 30-3c71bf6d7bac', 100 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating position: [ 'Roller Blinds 31-3c71bf6d7bac', 0 ]
[08/05/2023, 12:38:56] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 31-3c71bf6d7bac', 50 ]
[08/05/2023, 12:45:51] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 29-3c71bf6d7bac
[08/05/2023, 12:45:51] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 2a-3c71bf6d7bac

**Comment by gormanb** [comment]
Hi @fasif07 - I've just published `1.0.8-beta.2`, which attempts to better handle the network exceptions you've observed. Please give it a try and let me know how it goes! If the exceptions persist, then this may be an issue with Homebridge itself (see e.g. https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#error---eaddrinuse).

**Comment by fasif07** [comment]
Hi @gormanb. Thank you for the Beta, Just installed it and watched it for the last 30 mins. So far no crashes what so ever!!! Just some failed to update positions in Yellows but no reds.
I will keep an eye and report back if the issue resurfaces again

[06/06/2023, 22:12:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 46-3c71bf6d7bac', 100 ]
[06/06/2023, 22:12:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 47-3c71bf6d7bac', 100 ]
[06/06/2023, 22:12:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 49-3c71bf6d7bac', 50 ]
[06/06/2023, 22:12:24] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 50-3c71bf6d7bac', 50 ]
[06/06/2023, 22:12:29] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 55-3c71bf6d7bac', 100 ]
**[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 41-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 42-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 43-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 44-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 45-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 46-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 47-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 48-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 49-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 50-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 51-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 52-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 53-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 54-3c71bf6d7bac
[06/06/2023, 22:12:49] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 55-3c71bf6d7bac
[06/06/2023, 22:12:50] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 56-3c71bf6d7bac
[06/06/2023, 22:12:50] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 57-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 41-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 42-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 43-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 44-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 45-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 46-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 47-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 48-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 49-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 50-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 51-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 52-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 53-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 54-3c71bf6d7bac
[06/06/2023, 22:12:54] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 55-3c71bf6d7bac
[06/06/2023, 22:12:55] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 56-3c71bf6d7bac
[06/06/2023, 22:12:55] [homebridge-connector-hub] Periodic refresh failed: Roller Blinds 57-3c71bf6d7bac**
[06/06/2023, 22:13:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 41-3c71bf6d7bac', 100 ]
[06/06/2023, 22:13:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 42-3c71bf6d7bac', 100 ]
[06/06/2023, 22:13:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 43-3c71bf6d7bac', 100 ]
[06/06/2023, 22:13:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 45-3c71bf6d7bac', 100 ]
[06/06/2023, 22:13:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 47-3c71bf6d7bac', 100 ]
[06/06/2023, 22:13:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 49-3c71bf6d7bac', 50 ]
[06/06/2023, 22:13:24] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 50-3c71bf6d7bac', 50 ]
[06/06/2023, 22:13:24] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 54-3c71bf6d7bac', 100 ]
[06/06/2023, 22:13:29] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 55-3c71bf6d7bac', 100 ]
[06/06/2023, 22:14:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 43-3c71bf6d7bac', 100 ]
[06/06/2023, 22:14:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 44-3c71bf6d7bac', 100 ]
[06/06/2023, 22:14:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 45-3c71bf6d7bac', 100 ]
[06/06/2023, 22:14:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 46-3c71bf6d7bac', 100 ]
[06/06/2023, 22:14:23] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 49-3c71bf6d7bac', 50 ]
[06/06/2023, 22:14:24] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 50-3c71bf6d7bac', 50 ]
[06/06/2023, 22:14:24] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 52-3c71bf6d7bac', 100 ]
[06/06/2023, 22:14:24] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 54-3c71bf6d7bac', 100 ]
[06/06/2023, 22:14:29] [homebridge-connector-hub] Updating battery: [ 'Roller Blinds 55-3c71bf6d7bac', 100 ]

Thank you so much once again!

**Comment by gormanb** [comment]
Glad to hear that everything is working OK for you now, @fasif07! I'll publish release version `1.0.8` and close out this issue later today.
